server:
  port: ${PORT:9000}
spring:
  application:
    name: prostore-test-client-1.0
logging:
  level:
    ru.programstore.prostore: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
app:
  testServiceName: prostore-test-service-1.0
